# Project Name
spring.application.name=SalaryBudgetAPI

# Server Configuration
server.port=8089

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:budgetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enables the H2 Console (so you can see your data at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the console (helpful for learning)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
